name: gh_trend
description: GitHub trending (developers & repositories) scraper for dart and flutter.
version: 1.1.0
homepage: https://github.com/xamantra/gh_trend

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
 http: ^0.13.1
 html: ^0.15.0
 equatable: ^2.0.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
