/// List of possible programming languages from GitHub.
const ghProgrammingLanguages = {
  '1c-enterprise': '1C Enterprise',
  'abap': 'ABAP',
  'abnf': 'ABNF',
  'actionscript': 'ActionScript',
  'ada': 'Ada',
  'adobe-font-metrics': 'Adobe Font Metrics',
  'agda': 'Agda',
  'ags-script': 'AGS Script',
  'alloy': 'Alloy',
  'alpine-abuild': 'Alpine Abuild',
  'ampl': 'AMPL',
  'angelscript': 'AngelScript',
  'ant-build-system': 'Ant Build System',
  'antlr': 'ANTLR',
  'apacheconf': 'ApacheConf',
  'apex': 'Apex',
  'api-blueprint': 'API Blueprint',
  'apl': 'APL',
  'apollo-guidance-computer': 'Apollo Guidance Computer',
  'applescript': 'AppleScript',
  'arc': 'Arc',
  'asciidoc': 'AsciiDoc',
  'asn.1': 'ASN.1',
  'asp': 'ASP',
  'aspectj': 'AspectJ',
  'assembly': 'Assembly',
  'ats': 'ATS',
  'augeas': 'Augeas',
  'autohotkey': 'AutoHotkey',
  'autoit': 'AutoIt',
  'awk': 'Awk',
  'ballerina': 'Ballerina',
  'batchfile': 'Batchfile',
  'befunge': 'Befunge',
  'bison': 'Bison',
  'bitbake': 'BitBake',
  'blade': 'Blade',
  'blitzbasic': 'BlitzBasic',
  'blitzmax': 'BlitzMax',
  'bluespec': 'Bluespec',
  'boo': 'Boo',
  'brainfuck': 'Brainfuck',
  'brightscript': 'Brightscript',
  'bro': 'Bro',
  'c': 'C',
  'c%23': 'C#',
  'c%2B%2B': 'C++',
  'c-objdump': 'C-ObjDump',
  'c2hs-haskell': 'C2hs Haskell',
  'cap\'n-proto': 'Cap\'n Proto',
  'cartocss': 'CartoCSS',
  'ceylon': 'Ceylon',
  'chapel': 'Chapel',
  'charity': 'Charity',
  'chuck': 'ChucK',
  'cirru': 'Cirru',
  'clarion': 'Clarion',
  'clean': 'Clean',
  'click': 'Click',
  'clips': 'CLIPS',
  'clojure': 'Clojure',
  'closure-templates': 'Closure Templates',
  'cmake': 'CMake',
  'cobol': 'COBOL',
  'coffeescript': 'CoffeeScript',
  'coldfusion': 'ColdFusion',
  'coldfusion-cfc': 'ColdFusion CFC',
  'collada': 'COLLADA',
  'common-lisp': 'Common Lisp',
  'common-workflow-language': 'Common Workflow Language',
  'component-pascal': 'Component Pascal',
  'cool': 'Cool',
  'coq': 'Coq',
  'cpp-objdump': 'Cpp-ObjDump',
  'creole': 'Creole',
  'crystal': 'Crystal',
  'cson': 'CSON',
  'csound': 'Csound',
  'csound-document': 'Csound Document',
  'csound-score': 'Csound Score',
  'css': 'CSS',
  'csv': 'CSV',
  'cuda': 'Cuda',
  'cweb': 'CWeb',
  'cycript': 'Cycript',
  'cython': 'Cython',
  'd': 'D',
  'd-objdump': 'D-ObjDump',
  'darcs-patch': 'Darcs Patch',
  'dart': 'Dart',
  'dataweave': 'DataWeave',
  'desktop': 'desktop',
  'diff': 'Diff',
  'digital-command-language': 'DIGITAL Command Language',
  'dm': 'DM',
  'dns-zone': 'DNS Zone',
  'dockerfile': 'Dockerfile',
  'dogescript': 'Dogescript',
  'dtrace': 'DTrace',
  'dylan': 'Dylan',
  'e': 'E',
  'eagle': 'Eagle',
  'easybuild': 'Easybuild',
  'ebnf': 'EBNF',
  'ec': 'eC',
  'ecere-projects': 'Ecere Projects',
  'ecl': 'ECL',
  'eclipse': 'ECLiPSe',
  'edje-data-collection': 'Edje Data Collection',
  'edn': 'edn',
  'eiffel': 'Eiffel',
  'ejs': 'EJS',
  'elixir': 'Elixir',
  'elm': 'Elm',
  'emacs-lisp': 'Emacs Lisp',
  'emberscript': 'EmberScript',
  'eq': 'EQ',
  'erlang': 'Erlang',
  'f%23': 'F#',
  'factor': 'Factor',
  'fancy': 'Fancy',
  'fantom': 'Fantom',
  'filebench-wml': 'Filebench WML',
  'filterscript': 'Filterscript',
  'fish': 'fish',
  'flux': 'FLUX',
  'formatted': 'Formatted',
  'forth': 'Forth',
  'fortran': 'Fortran',
  'freemarker': 'FreeMarker',
  'frege': 'Frege',
  'g-code': 'G-code',
  'game-maker-language': 'Game Maker Language',
  'gams': 'GAMS',
  'gap': 'GAP',
  'gcc-machine-description': 'GCC Machine Description',
  'gdb': 'GDB',
  'gdscript': 'GDScript',
  'genie': 'Genie',
  'genshi': 'Genshi',
  'gentoo-ebuild': 'Gentoo Ebuild',
  'gentoo-eclass': 'Gentoo Eclass',
  'gerber-image': 'Gerber Image',
  'gettext-catalog': 'Gettext Catalog',
  'gherkin': 'Gherkin',
  'glsl': 'GLSL',
  'glyph': 'Glyph',
  'gn': 'GN',
  'gnuplot': 'Gnuplot',
  'go': 'Go',
  'golo': 'Golo',
  'gosu': 'Gosu',
  'grace': 'Grace',
  'gradle': 'Gradle',
  'grammatical-framework': 'Grammatical Framework',
  'graph-modeling-language': 'Graph Modeling Language',
  'graphql': 'GraphQL',
  'graphviz-(dot)': 'Graphviz (DOT)',
  'groovy': 'Groovy',
  'groovy-server-pages': 'Groovy Server Pages',
  'hack': 'Hack',
  'haml': 'Haml',
  'handlebars': 'Handlebars',
  'harbour': 'Harbour',
  'haskell': 'Haskell',
  'haxe': 'Haxe',
  'hcl': 'HCL',
  'hlsl': 'HLSL',
  'html': 'HTML',
  'html%2Bdjango': 'HTML+Django',
  'html%2Becr': 'HTML+ECR',
  'html%2Beex': 'HTML+EEX',
  'html%2Berb': 'HTML+ERB',
  'html%2Bphp': 'HTML+PHP',
  'http': 'HTTP',
  'hy': 'Hy',
  'hyphy': 'HyPhy',
  'idl': 'IDL',
  'idris': 'Idris',
  'igor-pro': 'IGOR Pro',
  'inform-7': 'Inform 7',
  'ini': 'INI',
  'inno-setup': 'Inno Setup',
  'io': 'Io',
  'ioke': 'Ioke',
  'irc-log': 'IRC log',
  'isabelle': 'Isabelle',
  'isabelle-root': 'Isabelle ROOT',
  'j': 'J',
  'jasmin': 'Jasmin',
  'java': 'Java',
  'java-server-pages': 'Java Server Pages',
  'javascript': 'JavaScript',
  'jflex': 'JFlex',
  'jison': 'Jison',
  'jison-lex': 'Jison Lex',
  'jolie': 'Jolie',
  'json': 'JSON',
  'json5': 'JSON5',
  'jsoniq': 'JSONiq',
  'jsonld': 'JSONLD',
  'jsx': 'JSX',
  'julia': 'Julia',
  'jupyter-notebook': 'Jupyter Notebook',
  'kicad-layout': 'KiCad Layout',
  'kicad-legacy-layout': 'KiCad Legacy Layout',
  'kicad-schematic': 'KiCad Schematic',
  'kit': 'Kit',
  'kotlin': 'Kotlin',
  'krl': 'KRL',
  'labview': 'LabVIEW',
  'lasso': 'Lasso',
  'latte': 'Latte',
  'lean': 'Lean',
  'less': 'Less',
  'lex': 'Lex',
  'lfe': 'LFE',
  'lilypond': 'LilyPond',
  'limbo': 'Limbo',
  'linker-script': 'Linker Script',
  'linux-kernel-module': 'Linux Kernel Module',
  'liquid': 'Liquid',
  'literate-agda': 'Literate Agda',
  'literate-coffeescript': 'Literate CoffeeScript',
  'literate-haskell': 'Literate Haskell',
  'livescript': 'LiveScript',
  'llvm': 'LLVM',
  'logos': 'Logos',
  'logtalk': 'Logtalk',
  'lolcode': 'LOLCODE',
  'lookml': 'LookML',
  'loomscript': 'LoomScript',
  'lsl': 'LSL',
  'lua': 'Lua',
  'm': 'M',
  'm4': 'M4',
  'm4sugar': 'M4Sugar',
  'makefile': 'Makefile',
  'mako': 'Mako',
  'markdown': 'Markdown',
  'marko': 'Marko',
  'mask': 'Mask',
  'mathematica': 'Mathematica',
  'matlab': 'Matlab',
  'maven-pom': 'Maven POM',
  'max': 'Max',
  'maxscript': 'MAXScript',
  'mediawiki': 'MediaWiki',
  'mercury': 'Mercury',
  'meson': 'Meson',
  'metal': 'Metal',
  'minid': 'MiniD',
  'mirah': 'Mirah',
  'modelica': 'Modelica',
  'modula-2': 'Modula-2',
  'module-management-system': 'Module Management System',
  'monkey': 'Monkey',
  'moocode': 'Moocode',
  'moonscript': 'MoonScript',
  'mql4': 'MQL4',
  'mql5': 'MQL5',
  'mtml': 'MTML',
  'muf': 'MUF',
  'mupad': 'mupad',
  'myghty': 'Myghty',
  'ncl': 'NCL',
  'nearley': 'Nearley',
  'nemerle': 'Nemerle',
  'nesc': 'nesC',
  'netlinx': 'NetLinx',
  'netlinx%2Berb': 'NetLinx+ERB',
  'netlogo': 'NetLogo',
  'newlisp': 'NewLisp',
  'nextflow': 'Nextflow',
  'nginx': 'Nginx',
  'nim': 'Nim',
  'ninja': 'Ninja',
  'nit': 'Nit',
  'nix': 'Nix',
  'nl': 'NL',
  'nsis': 'NSIS',
  'nu': 'Nu',
  'numpy': 'NumPy',
  'objdump': 'ObjDump',
  'objective-c': 'Objective-C',
  'objective-c%2B%2B': 'Objective-C++',
  'objective-j': 'Objective-J',
  'ocaml': 'OCaml',
  'omgrofl': 'Omgrofl',
  'ooc': 'ooc',
  'opa': 'Opa',
  'opal': 'Opal',
  'opencl': 'OpenCL',
  'openedge-abl': 'OpenEdge ABL',
  'openrc-runscript': 'OpenRC runscript',
  'openscad': 'OpenSCAD',
  'opentype-feature-file': 'OpenType Feature File',
  'org': 'Org',
  'ox': 'Ox',
  'oxygene': 'Oxygene',
  'oz': 'Oz',
  'p4': 'P4',
  'pan': 'Pan',
  'papyrus': 'Papyrus',
  'parrot': 'Parrot',
  'parrot-assembly': 'Parrot Assembly',
  'parrot-internal-representation': 'Parrot Internal Representation',
  'pascal': 'Pascal',
  'pawn': 'PAWN',
  'pep8': 'Pep8',
  'perl': 'Perl',
  'perl-6': 'Perl 6',
  'php': 'PHP',
  'pic': 'Pic',
  'pickle': 'Pickle',
  'picolisp': 'PicoLisp',
  'piglatin': 'PigLatin',
  'pike': 'Pike',
  'plpgsql': 'PLpgSQL',
  'plsql': 'PLSQL',
  'pod': 'Pod',
  'pogoscript': 'PogoScript',
  'pony': 'Pony',
  'postcss': 'PostCSS',
  'postscript': 'PostScript',
  'pov-ray-sdl': 'POV-Ray SDL',
  'powerbuilder': 'PowerBuilder',
  'powershell': 'PowerShell',
  'processing': 'Processing',
  'prolog': 'Prolog',
  'propeller-spin': 'Propeller Spin',
  'protocol-buffer': 'Protocol Buffer',
  'public-key': 'Public Key',
  'pug': 'Pug',
  'puppet': 'Puppet',
  'pure-data': 'Pure Data',
  'purebasic': 'PureBasic',
  'purescript': 'PureScript',
  'python': 'Python',
  'python-console': 'Python console',
  'python-traceback': 'Python traceback',
  'qmake': 'QMake',
  'qml': 'QML',
  'r': 'R',
  'racket': 'Racket',
  'ragel': 'Ragel',
  'raml': 'RAML',
  'rascal': 'Rascal',
  'raw-token-data': 'Raw token data',
  'rdoc': 'RDoc',
  'realbasic': 'REALbasic',
  'reason': 'Reason',
  'rebol': 'Rebol',
  'red': 'Red',
  'redcode': 'Redcode',
  'regular-expression': 'Regular Expression',
  'ren\'py': 'Ren\'Py',
  'renderscript': 'RenderScript',
  'restructuredtext': 'reStructuredText',
  'rexx': 'REXX',
  'rhtml': 'RHTML',
  'ring': 'Ring',
  'rmarkdown': 'RMarkdown',
  'robotframework': 'RobotFramework',
  'roff': 'Roff',
  'rouge': 'Rouge',
  'rpc': 'RPC',
  'rpm-spec': 'RPM Spec',
  'ruby': 'Ruby',
  'runoff': 'RUNOFF',
  'rust': 'Rust',
  'sage': 'Sage',
  'saltstack': 'SaltStack',
  'sas': 'SAS',
  'sass': 'Sass',
  'scala': 'Scala',
  'scaml': 'Scaml',
  'scheme': 'Scheme',
  'scilab': 'Scilab',
  'scss': 'SCSS',
  'sed': 'sed',
  'self': 'Self',
  'shaderlab': 'ShaderLab',
  'shell': 'Shell',
  'shellsession': 'ShellSession',
  'shen': 'Shen',
  'slash': 'Slash',
  'slim': 'Slim',
  'smali': 'Smali',
  'smalltalk': 'Smalltalk',
  'smarty': 'Smarty',
  'smt': 'SMT',
  'solidity': 'Solidity',
  'sourcepawn': 'SourcePawn',
  'sparql': 'SPARQL',
  'spline-font-database': 'Spline Font Database',
  'sqf': 'SQF',
  'sql': 'SQL',
  'sqlpl': 'SQLPL',
  'squirrel': 'Squirrel',
  'srecode-template': 'SRecode Template',
  'stan': 'Stan',
  'standard-ml': 'Standard ML',
  'stata': 'Stata',
  'ston': 'STON',
  'stylus': 'Stylus',
  'sublime-text-config': 'Sublime Text Config',
  'subrip-text': 'SubRip Text',
  'sugarss': 'SugarSS',
  'supercollider': 'SuperCollider',
  'svg': 'SVG',
  'swift': 'Swift',
  'systemverilog': 'SystemVerilog',
  'tcl': 'Tcl',
  'tcsh': 'Tcsh',
  'tea': 'Tea',
  'terra': 'Terra',
  'tex': 'TeX',
  'text': 'Text',
  'textile': 'Textile',
  'thrift': 'Thrift',
  'ti-program': 'TI Program',
  'tla': 'TLA',
  'toml': 'TOML',
  'turing': 'Turing',
  'turtle': 'Turtle',
  'twig': 'Twig',
  'txl': 'TXL',
  'type-language': 'Type Language',
  'typescript': 'TypeScript',
  'unified-parallel-c': 'Unified Parallel C',
  'unity3d-asset': 'Unity3D Asset',
  'unix-assembly': 'Unix Assembly',
  'uno': 'Uno',
  'unrealscript': 'UnrealScript',
  'urweb': 'UrWeb',
  'vala': 'Vala',
  'vcl': 'VCL',
  'verilog': 'Verilog',
  'vhdl': 'VHDL',
  'vim-script': 'Vim script',
  'visual-basic': 'Visual Basic',
  'volt': 'Volt',
  'vue': 'Vue',
  'wavefront-material': 'Wavefront Material',
  'wavefront-object': 'Wavefront Object',
  'wdl': 'wdl',
  'web-ontology-language': 'Web Ontology Language',
  'webassembly': 'WebAssembly',
  'webidl': 'WebIDL',
  'wisp': 'wisp',
  'world-of-warcraft-addon-data': 'World of Warcraft Addon Data',
  'x10': 'X10',
  'xbase': 'xBase',
  'xc': 'XC',
  'xcompose': 'XCompose',
  'xml': 'XML',
  'xojo': 'Xojo',
  'xpages': 'XPages',
  'xpm': 'XPM',
  'xproc': 'XProc',
  'xquery': 'XQuery',
  'xs': 'XS',
  'xslt': 'XSLT',
  'xtend': 'Xtend',
  'yacc': 'Yacc',
  'yaml': 'YAML',
  'yang': 'YANG',
  'yara': 'YARA',
  'zephir': 'Zephir',
  'zimpl': 'Zimpl',
};
